# fly.toml app configuration file generated for apiuny on 2023-05-27T19:19:33-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "apiuny"
primary_region = "gru"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
